Implement basic functionality for crypto stats
josephroberts/rust-crypto-tracker pull request #1
Opened 2017-06-23 16:25 UTC by josephroberts

```
$ ./rust-crypto-ticker -c bitcoin -f "{symbol} \${price_usd} {percent_change_24h}%"
BTC $2749.82 1.17%
```

2017-06-23 18:18 UTC, CameronDiver requested changes

2017-06-23 18:18 UTC, CameronDiver commented on README.md
> +$ ./target/release/rust-crypto-tracker -h
This should be just the executable name.

2017-06-23 18:18 UTC, CameronDiver commented on rustfmt.toml
> +max_width = 1024
This shouldn't be here.

2017-06-23 18:18 UTC, CameronDiver commented on src/main.rs
> +                    "{name}, {symbol}, {rank}, {price_usd}, {price_btc}, {24h_volume_usd}, {market_cap_usd}, {available_supply}, {total_supply}, {percent_change_1h}, {percent_change_24h}, {percent_ch
I think if you just have `"several" "string" "literals"` it should be fine.

2017-06-23 18:18 UTC, CameronDiver commented on src/main.rs
> +    let mut response = client.get(url.to_str().unwrap()).send().unwrap();
We should make an issue to address the error handling here.

2017-06-23 18:21 UTC, josephroberts commented on src/main.rs
> +    let mut response = client.get(url.to_str().unwrap()).send().unwrap();
#1

2017-06-30 09:01 UTC, CameronDiver approved these changes

2017-06-30 09:59 UTC, merged